### ISSUE TITLE
Exclude variables from JSON data

### ISSUE THREAD

**Issue by BasThomas** [turowicz/swift-serializer#11]
All variables, including description (Printable), debugDescription(debugPrintable) and hashValue (Hashable) end up in the JSON. Is there a way to exclude these that I have overlooked? It would be a great addition.

**Comment by turowicz** [comment]
What would be a good feature is a way of excluding fields and changing their serialized names (in case somebody needed JS a name that is not compatible with the swift compiler). Anyone have any ideas about possible approaches?

**Comment by turowicz** [comment]
cc @tomaskraina @nazywamsiepawel @imamark @krzyzanowskim

**Comment by mpavlinsky** [comment]
Do you have a code sample that shows this? I don't see it with:
```
public class TestClass : Serializable, Printable {
    var name = "Test Name";
    
    override public var description: String {
        return "Test Description"
    }
}

var test = TestClass();
println(test.toDictionary());
// {
//   name = "Test Name";
// }
```

**Comment by BasThomas** [comment]
```swift
class Test: Serializable {
    
    var test: String!
    
    override init() {
        self.test = "thing"
    }
}

extension Test: Printable {
    
    override var description: String {
        return "\(self.test)"
    }
}

println(Test().toJsonString())

// {
//    "test":"thing",
//    "description":"thing"
// }
```

**Comment by mpavlinsky** [comment]
What Xcode version are you using? The same code you posted doesn't have that issue on Xcode 6.3.1 (Swift 1.2)

**Comment by BasThomas** [comment]
Strange. 6.3.2.

**Comment by BasThomas** [comment]
It seems like it was an issue with an older version of this project; I was using Cocoapods.

Would still be nice to be able to explicitly exclude values, though. :)
