### ISSUE TITLE
This is a crime 

### ISSUE THREAD

**Issue by komodoswitch** [turowicz/swift-serializer#40]
public func toDictionary() -> NSDictionary {
        let propertiesDictionary = SortedDictionary()
        let mirror = Mirror(reflecting: self)
        for (propName, propValue) in mirror.children {
            if let propValue: AnyObject = self.unwrap(propValue) as? AnyObject, propName = propName {
                if let serializablePropValue = propValue as? Serializable {
                    setValue(propertiesDictionary, value: serializablePropValue.toDictionary(), forKey: propName)
                } else if let arrayPropValue = propValue as? [Serializable] {
                    let subArray = arrayPropValue.toNSDictionaryArray()
                    setValue(propertiesDictionary, value: subArray, forKey: propName)
                } else if propValue is Int || propValue is Double || propValue is Float || propValue is Bool {
                    setValue(propertiesDictionary, value: propValue, forKey: propName)
                } else if let dataPropValue = propValue as? NSData {
                    setValue(propertiesDictionary,
                        value: dataPropValue.base64EncodedStringWithOptions(.Encoding64CharacterLineLength), forKey: propName)
                } else if let datePropValue = propValue as? NSDate {
                    setValue(propertiesDictionary, value: datePropValue.timeIntervalSince1970, forKey: propName)
                } else {
                    setValue(propertiesDictionary, value: propValue, forKey: propName)
                }
            } else if let propValue: Int8 = propValue as? Int8 {
                setValue(propertiesDictionary, value: NSNumber(char: propValue), forKey: propName!)
            } else if let propValue: Int16 = propValue as? Int16 {
                setValue(propertiesDictionary, value: NSNumber(short: propValue), forKey: propName!)
            } else if let propValue: Int32 = propValue as? Int32 {
                setValue(propertiesDictionary, value: NSNumber(int: propValue), forKey: propName!)
            } else if let propValue: Int64 = propValue as? Int64 {
                setValue(propertiesDictionary, value: NSNumber(longLong: propValue), forKey: propName!)
            } else if let propValue: UInt8 = propValue as? UInt8 {
                setValue(propertiesDictionary, value: NSNumber(unsignedChar: propValue), forKey: propName!)
            } else if let propValue: UInt16 = propValue as? UInt16 {
                setValue(propertiesDictionary, value: NSNumber(unsignedShort: propValue), forKey: propName!)
            } else if let propValue: UInt32 = propValue as? UInt32 {
                setValue(propertiesDictionary, value: NSNumber(unsignedInt: propValue), forKey: propName!)
            } else if let propValue: UInt64 = propValue as? UInt64 {
                setValue(propertiesDictionary, value: NSNumber(unsignedLongLong: propValue), forKey: propName!)
            } else if isEnum(propValue) {
                setValue(propertiesDictionary, value: "\(propValue)", forKey: propName!)
            }
        }

        return propertiesDictionary
    }

**Comment by turowicz** [comment]
@komodoswitch agreed, please submit your pull request
