### ISSUE TITLE
Publish to Cocoapods?

### ISSUE THREAD

**Issue by richardPFisk** [turowicz/swift-serializer#41]
Thank you for your time and effort in creating this library. Would it be possible for you to publish the latest version of your code to Cocoapods?

**Comment by turowicz** [comment]
@richardPFisk I will be resurrecting this repository this weekend.

**Comment by sjturley** [comment]
@turowicz Can you publish version 0.6 to Cocoapods?

**Comment by turowicz** [comment]
@sjturley I will ask @krzyzanowskim because he owns the pod.

**Comment by krzyzanowskim** [comment]
What's done is done.

**Comment by turowicz** [comment]
Kudos @krzyzanowskim !
